<SettingsScreen>:
    name: "settings"

    BoxLayout:
        orientation: "vertical"
        size_hint: 1,1
        spacing: 10
        padding: [20, 20]

        Label:
            id: settings_label
            text: "Settings screen"
            font_size: 50
            font_name: "SecondaryFont"
            color: 0,0,0,1
            halign: "center"
            valign: "middle"
            size_hint_y: None
            height: self.texture_size[1]
            pos_hint: {"center_y": 0.5}